# Generated by Django 3.2.16 on 2024-02-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='correct_solved',
            field=models.PositiveIntegerField(default=0, verbose_name='밎은 문제 갯수'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_solved',
            field=models.PositiveIntegerField(default=0, verbose_name='총 시도한 문제 갯수'),
        ),
    ]
