# Generated by Django 3.2.16 on 2024-01-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '강좌 카테고리', 'verbose_name_plural': '강좌 카테고리'},
        ),
    ]
