# Generated by Django 3.2.16 on 2024-01-18 15:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import like_korean.apps.level_tests.models.index
import like_korean.bases.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created'], 'verbose_name': '문항', 'verbose_name_plural': '문항'},
        ),
        migrations.AddField(
            model_name='question',
            name='is_audio',
            field=models.BooleanField(default=False, verbose_name='오디오 여부'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_multiple_choice',
            field=models.BooleanField(default=True, verbose_name='객관식 여부'),
        ),
        migrations.AlterField(
            model_name='questionimage',
            name='image',
            field=models.ImageField(upload_to=like_korean.apps.level_tests.models.index.question_image_path, verbose_name='이미지'),
        ),
        migrations.CreateModel(
            name='QuestionAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('audio', models.FileField(upload_to=like_korean.apps.level_tests.models.index.question_audio_path, verbose_name='오디오')),
                ('audio_url', models.URLField(blank=True, null=True, verbose_name='오디오 URL')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_audios', to='level_tests.question')),
            ],
            options={
                'abstract': False,
            },
            bases=(like_korean.bases.models.UpdateMixin, models.Model),
        ),
    ]
