# Generated by Django 3.2.16 on 2024-01-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='문제 난이도'),
        ),
    ]
