# Generated by Django 3.2.16 on 2024-01-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0002_auto_20240118_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_url',
            field=models.TextField(blank=True, null=True, verbose_name='오디오 url'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.TextField(blank=True, null=True, verbose_name='이미지 url'),
        ),
    ]
