# Generated by Django 3.2.16 on 2024-01-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0003_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.TextField(blank=True, choices=[('GRAMMAR', '문법'), ('READING', '읽기'), ('WRITING', '쓰기'), ('SPEAKING', '읽기'), ('GALLERY', 'GALLERY'), ('VIDEO', 'VIDEO')], null=True, verbose_name='문제 유형'),
        ),
    ]
