# Generated by Django 3.2.16 on 2024-01-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0004_auto_20240127_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='점수'),
        ),
    ]
