# Generated by Django 3.2.16 on 2024-01-29 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0005_question_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionaudio',
            options={'ordering': ['-created'], 'verbose_name': '문제 오디오', 'verbose_name_plural': '문제 오디오'},
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='Test',
            new_name='test',
        ),
        migrations.AlterModelTable(
            name='questionaudio',
            table='question_audios',
        ),
    ]
