# Generated by Django 3.2.16 on 2024-02-05 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import like_korean.bases.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0006_alter_question_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('name', models.TextField(unique=True, verbose_name='시험 카테고리')),
            ],
            options={
                'verbose_name': '시험 카테고리',
                'verbose_name_plural': '시험 카테고리',
                'db_table': 'test_categories',
                'ordering': ['-created'],
            },
            bases=(like_korean.bases.models.UpdateMixin, models.Model),
        ),
        migrations.AddField(
            model_name='test',
            name='attempt_count',
            field=models.IntegerField(default=0, verbose_name='응시 횟수'),
        ),
        migrations.AddField(
            model_name='test',
            name='avg_score',
            field=models.FloatField(blank=True, null=True, verbose_name='평균 점수'),
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='level_tests.testcategory'),
        ),
    ]
