# Generated by Django 3.2.16 on 2024-02-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0007_auto_20240205_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='avg_score',
            field=models.FloatField(default=0, verbose_name='평균 점수'),
        ),
    ]
