# Generated by Django 3.2.16 on 2024-02-12 04:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import like_korean.apps.level_tests.models.index
import like_korean.bases.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0008_alter_test_avg_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_image',
            field=models.BooleanField(default=False, verbose_name='이미지 여부'),
        ),
        migrations.CreateModel(
            name='ChoiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('image', models.ImageField(upload_to=like_korean.apps.level_tests.models.index.choice_image_path, verbose_name='이미지')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='이미지 URL')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_images', to='level_tests.choice')),
            ],
            options={
                'verbose_name': '객관식 문항 이미지',
                'verbose_name_plural': '객관식 문항 이미지',
                'db_table': 'choice_images',
                'ordering': ['-created'],
            },
            bases=(like_korean.bases.models.UpdateMixin, models.Model),
        ),
    ]
