# Generated by Django 3.2.16 on 2024-02-12 04:49

from django.db import migrations, models
import like_korean.apps.level_tests.models.index


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0009_auto_20240212_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=like_korean.apps.level_tests.models.index.choice_image_path, verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='choice',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='이미지 URL'),
        ),
        migrations.DeleteModel(
            name='ChoiceImage',
        ),
    ]
