# Generated by Django 3.2.16 on 2024-02-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0010_auto_20240212_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.TextField(blank=True, null=True, verbose_name='선택지'),
        ),
    ]
