# Generated by Django 3.2.16 on 2024-02-12 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import like_korean.bases.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('level_tests', '0011_alter_choice_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('is_solved', models.BooleanField(verbose_name='정답 유무')),
                ('description', models.TextField(blank=True, null=True, verbose_name='오답 설명')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvings', to='level_tests.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvings', to='level_tests.test')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solvings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '문제 풀이',
                'verbose_name_plural': '문제 풀이',
                'db_table': 'solvings',
                'ordering': ['-created'],
            },
            bases=(like_korean.bases.models.UpdateMixin, models.Model),
        ),
    ]
