# Generated by Django 3.2.16 on 2024-02-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0012_solving'),
    ]

    operations = [
        migrations.AddField(
            model_name='solving',
            name='question_name',
            field=models.TextField(blank=True, null=True, verbose_name='문제 이름'),
        ),
        migrations.AddField(
            model_name='solving',
            name='test_name',
            field=models.TextField(blank=True, null=True, verbose_name='테스트 이름'),
        ),
    ]
