# Generated by Django 3.2.16 on 2024-02-18 08:01

from django.db import migrations, models
import like_korean.apps.nationalities.models.index


class Migration(migrations.Migration):

    dependencies = [
        ('nationalities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationality',
            name='notation_name',
        ),
        migrations.AddField(
            model_name='nationality',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='국가코드'),
        ),
        migrations.AddField(
            model_name='nationality',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=like_korean.apps.nationalities.models.index.nationality_image_path, verbose_name='국기 이미지'),
        ),
        migrations.AddField(
            model_name='nationality',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='이미지 URL'),
        ),
    ]
