# Generated by Django 3.2.16 on 2024-02-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalities', '0002_auto_20240218_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationality',
            name='eng_name',
            field=models.TextField(blank=True, null=True, verbose_name='국가명(영문)'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='name',
            field=models.TextField(unique=True, verbose_name='국가명(한글)'),
        ),
    ]
