# Generated by Django 3.2.16 on 2024-01-11 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import like_korean.bases.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('method', models.TextField(choices=[('credit_card', 'Credit Card'), ('cash', 'Cash'), ('event', 'Event'), ('etc', 'etc'), ('refund', 'refund')], default='etc')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='유저 이메일')),
                ('lecture_name', models.TextField(blank=True, null=True, verbose_name='강좌 이름')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='lectures.lecture')),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제',
                'db_table': 'payments',
                'ordering': ['-created'],
            },
            bases=(like_korean.bases.models.UpdateMixin, models.Model),
        ),
    ]
