# Generated by Django 3.2.16 on 2024-01-11 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import like_korean.apps.lectures.models.index
import like_korean.apps.lectures.models.mixins_lecture.image
import like_korean.bases.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to=like_korean.apps.lectures.models.mixins_lecture.image.image_path, verbose_name='썸네일 이미지')),
                ('thumbnail_image_url', models.URLField(blank=True, null=True, verbose_name='썸네일 이미지 URL')),
                ('name', models.TextField(blank=True, null=True, verbose_name='강의 이름')),
                ('description', models.TextField(blank=True, null=True, verbose_name='강의 설명')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='강의 비용')),
                ('_owner_id', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='강사 id')),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='강사 email')),
            ],
            options={
                'verbose_name': '강의',
                'verbose_name_plural': '강의',
                'db_table': 'lecture',
                'ordering': ['-created'],
            },
            bases=(like_korean.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LectureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('image', models.ImageField(upload_to=like_korean.apps.lectures.models.index.lecture_image_path, verbose_name='이미지')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='이미지 URL')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='썸네일 이미지')),
                ('thumbnail_image_url', models.URLField(blank=True, null=True, verbose_name='썸네일 이미지 URL')),
            ],
            options={
                'verbose_name': '강의 이미지',
                'verbose_name_plural': '강의 이미지',
                'db_table': 'lecture_images',
                'ordering': ['-created'],
            },
            bases=(like_korean.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LectureVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('_lecture_id', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='강의 id')),
                ('lecture_name', models.TextField(blank=True, null=True, verbose_name='강의명')),
                ('unit_name', models.TextField(blank=True, null=True, verbose_name='단원명')),
                ('name', models.TextField(blank=True, null=True, verbose_name='영상 제목')),
                ('description', models.TextField(blank=True, null=True, verbose_name='영상 설명')),
                ('video', models.FileField(upload_to='', verbose_name='비디오')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='비디오 URL')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='썸네일 이미지')),
                ('thumbnail_image_url', models.URLField(blank=True, null=True, verbose_name='썸네일 이미지 URL')),
            ],
            options={
                'verbose_name': '강의 비디오',
                'verbose_name_plural': '강의 비디오',
                'db_table': 'lecture_videos',
                'ordering': ['-created'],
            },
            bases=(like_korean.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(blank=True, choices=[('', '')], default='', max_length=100, no_check_for_status=True, null=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, verbose_name='status changed')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('name', models.TextField(verbose_name='단원 명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='단원 설명')),
                ('_lecture_id', models.SmallIntegerField(blank=True, null=True, verbose_name='강의 id')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='lectures.lecture')),
            ],
            options={
                'verbose_name': '강의 단원',
                'verbose_name_plural': '강의 단원',
                'db_table': 'units',
                'ordering': ['-created'],
            },
            bases=(like_korean.bases.models.UpdateMixin, models.Model),
        ),
    ]
