# Generated by Django 3.2.16 on 2024-01-13 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['-created'], 'verbose_name': '강좌', 'verbose_name_plural': '강좌'},
        ),
        migrations.AlterModelOptions(
            name='lectureimage',
            options={'ordering': ['-created'], 'verbose_name': '강좌 이미지', 'verbose_name_plural': '강좌 이미지'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-created'], 'verbose_name': '강좌 단원', 'verbose_name_plural': '강좌 단원'},
        ),
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='강좌 설명'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='강좌 이름'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='강좌 비용'),
        ),
        migrations.AlterField(
            model_name='lectureimage',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_images', to='lectures.lecture', verbose_name='강좌'),
        ),
        migrations.AlterField(
            model_name='lecturevideo',
            name='_lecture_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='강좌 id'),
        ),
        migrations.AlterField(
            model_name='lecturevideo',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_videos', to='lectures.lecture', verbose_name='강좌'),
        ),
        migrations.AlterField(
            model_name='lecturevideo',
            name='lecture_name',
            field=models.TextField(blank=True, null=True, verbose_name='강좌명'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='_lecture_id',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='강좌 id'),
        ),
    ]
